import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Script de estudos de Análise Exploratória de Dados (AED).
# O arquivo reúne exemplos de estatística descritiva e visualização
# com `pandas`, `matplotlib` e `seaborn` ao longo das aulas.

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfpT4OCWsQ_SRwEiYKmSXKpJVp6ppbGW
"""

import pandas as pd

# ============================================================
# Aula inicial: média, mediana e distribuição de notas
# ============================================================

"""# função mean
A função mean() calcula a mediana de valores numéricos em uma coluna de um DataFrame, ajudando a entender a tendência central dos dados.


"""

notas = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/ml-latest-small/ratings.csv")
media = notas["rating"].mean()
media

notas

notas["rating"].plot(kind = 'hist')

notas["rating"].median()

mediana = notas["rating"].median()
media = notas["rating"].mean()
print(f"Mediana é {mediana}")
print(f"A media é {media}")

notas["rating"].describe()

"""O seaborn é uma biblioteca expecificamente dedidaca a graficos"""



sns.boxplot(notas["rating"])

"""Criação de dataframe simples:

"""



# Criando um DataFrame simples
dados = { 'Nome': ['Mirla', 'Ana', 'Daniel'],
   'Idade': [25, 30, 35],
              'Salario': [5000, 6000, 8000]}
df = pd.DataFrame(dados)
df

filmes = pd.read_csv("./sample_data/movies.csv")
filmes.columns = "filmeId", "Titulo", "Genero"
filmes.head()

filmes

"""O query é utilizado para selecionar um dado expecifico por exemplo, abaixo é o filme toy story da tabela == 2"""

notas.query("movieId==1")["rating"].mean()

"""Abaixo é o filme jumanji == 2"""

notas.query("movieId==2")["rating"].mean()

"""Calcular a media de cada um dos filmes : Group BY


"""

medias_por_filme = notas.groupby("movieId")["rating"].mean()
medias_por_filme.head()

medias_por_filme.plot(kind="hist")

"""Para a análise, foram pedidas duas ações:

A soma do valor total arrecadado com as vendas de 'Ratatouille' no período;
Frequência dos métodos de pagamento para o “Ratatouille”.
"""

sns.boxplot(medias_por_filme)

medias_por_filme.describe(

)




sns.displot(medias_por_filme, kde ="True")
plt.title("Histograma das médias dos filmes")

# Leitura de outra base TMDB para exemplos seguintes
tmdb = pd.read_csv("./sample_data/tmdb_5000_credits.csv")

# aula 03

# ============================================================
# Aula 03: distribuição de orçamento, receita e idiomas
# ============================================================

# Carrega o dataset de filmes da internet
tmdb = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/tmdb_5000_movies.csv")
# Mostra as primeiras linhas
tmdb.head()

# Mostra a distribuição da receita
sns.displot(tmdb["revenue"])
plt.title("Distribuição da receita dos filmes")
plt.show()

# Mostra a distribuição do orçamento
sns.displot(tmdb["budget"])
plt.title("Distribuição do orçamento dos filmes")
plt.show()

# Exibe informações gerais das colunas
tmdb.info()

# Filtra apenas filmes com faturamento maior que zero
com_faturamento = tmdb.query("revenue > 0")
sns.displot(com_faturamento["revenue"])

# Lista os idiomas originais disponíveis
tmdb["original_language"].unique()

# Conta quantos filmes existem por idioma
tmdb["original_language"].value_counts()
# aula 03

# Acessa índice e valores da contagem de idiomas
tmdb["original_language"].value_counts().index
tmdb["original_language"].value_counts().values

# Cria tabela com idioma e total de filmes
contagem_de_lingua = tmdb["original_language"].value_counts().to_frame().reset_index()
contagem_de_lingua.columns = ["original_language", "total"]
contagem_de_lingua.head()

# Gráfico de contagem por idioma
sns.countplot(data=tmdb, x="original_language")

# Gráfico de barras com a tabela criada
sns.barplot(x="original_language", y = "total", data = contagem_de_lingua)

sns.countplot(data=tmdb, x="original_language")

# Calcula total geral, total em inglês e total dos demais
total_por_lingua = tmdb["original_language"].value_counts()
total_geral = total_por_lingua.sum()
total_de_ingles = total_por_lingua.loc["en"]
total_do_resto = total_geral - total_de_ingles
print(total_geral, total_de_ingles, total_do_resto)

# Cria novo dataframe comparando inglês vs outros
dados = {
  "lingua" : ["ingles", "outros"],
  "total" : [total_de_ingles, total_do_resto]
}
dados = pd.DataFrame(dados)
dados

# Mostra gráfico final comparativo
sns.barplot(x="lingua", y="total", data = dados)

# Aula 04

# ============================================================
# Aula 04: relação entre orçamento e receita por idioma
# ============================================================

# Importando a base de dados
tmdb = pd.read_csv("https://raw.githubusercontent.com/alura-cursos/data-science-analise-exploratoria/main/Aula_0/tmdb_5000_movies.csv")

# Filtrando os dados para as colunas desejadas
dados = tmdb[["title", "original_language", "budget", "revenue"]]
linguas = ["fr", "es", "de"]

# Mantendo dados com valores de receita e orçamento válidos e nas línguas desejadas (fr, es, de)
fr_es_de_com_revenue_e_budget = dados.query("revenue > 0 and budget > 0 and original_language == @linguas")

# Construindo o gráfico de dispersão mais a reta de regressão linear para cada caso
sns.lmplot(data=fr_es_de_com_revenue_e_budget, x="budget", y="revenue", col="original_language", 
           hue="original_language", ci=None, height=4, scatter_kws={"s": 30, "alpha": 0.5})



# Aula 05

# ============================================================
# Aula 05: análise de idiomas não ingleses
# ============================================================

total_de_outros_filmes_por_lingua = tmdb.query("original_language != 'en'")["original_language"].value_counts()
total_de_outros_filmes_por_lingua.head()

sns.countplot(data=tmdb.query("original_language != 'en'"), x="original_language")

sns.countplot(data=tmdb.query("original_language != 'en'"),
              order=total_de_outros_filmes_por_lingua.index,
              hue="original_language",
              x="original_language")

plt.figure(figsize=(16, 8))
sns.countplot(data=tmdb.query("original_language != 'en'"),
              order=total_de_outros_filmes_por_lingua.index,
              palette="mako",
              hue="original_language",
              hue_order=total_de_outros_filmes_por_lingua.index,
              x="original_language")

#prompt : extraia as notas dos dois filmes em variaveis distintas

import pandas as pd
import numpy as np

# ============================================================
# Exercícios extras: desvio padrão, média e mediana
# ============================================================

# Criando DataFrame de exemplo

dados = np.array([[100, 120, 90, 110, 130], [80, 150, 70, 140, 60]])

df = pd.DataFrame(dados, index = ["Semana 1", "Semana 2"],
                  columns= ["Segunda", "Terça", "Quarta", "Quinta", "Sexta"])

# Calculando o desvio padrão das visitas por semana
desvio_padrao_semana1 = df.loc["Semana 1"].std()
desvio_padrao_semana2 = df.loc["Semana 2"].std()

print(df)
print("\nDesvio Padrão da Semana 1:", round(desvio_padrao_semana1, 2))
print("Desvio Padrão da Semana 2:", round(desvio_padrao_semana2, 2))

notas_do_toy_story = notas.query("filmeId==1")["nota"]
notas_do_jumanji = notas.query("filmeId==2")["nota"]

# Observação: este trecho usa os nomes de colunas `filmeId` e `nota`.
# Caso a base esteja com nomes em inglês (`movieId` e `rating`),
# ajuste os nomes das colunas antes de executar.

media_do_toy_story = notas_do_toy_story.mean()
media_do_jumanji = notas_do_jumanji.mean()

print(media_do_toy_story, media_do_jumanji)

mediana_do_toy_story = notas_do_toy_story.median()
mediana_do_jumanji = notas_do_jumanji.median()

print(f"Média do Toy Story {media_do_toy_story}")
print(f"Mediana do Toy Story {mediana_do_toy_story }" )
print(f"Média do Jumanji {media_do_jumanji }")
print(f"Mediana do Jumanji {mediana_do_jumanji }" ) 

import numpy as np 
filme1 = [2.5] * 10 + [3.5] * 10
filme2 = [5] * 10 + [1] * 10

media_filme1 = np.mean(filme1)
mediana_filme1 = np.median(filme1)

media_filme2 = np.mean(filme2)
mediana_filme2 = np.median(filme2)

print("Filme 1:")
print("Média:", media_filme1)
print("Mediana:", mediana_filme1)

print("\nFilme 2:")
print("Média:", media_filme2)
print("Mediana:", mediana_filme2)

plt.hist(filme1)
plt.hist(filme2)

plt.boxplot([filme1, filme2])

filme0 = [3.0] * 20 
np.std(filme0), np.std(filme1), np.std(filme2)

plt.boxplot([notas_do_toy_story, notas_do_jumanji])

# Boxplot comparando notas dos dois filmes no DataFrame `notas`
sns.boxplot(data=notas.query("filmeId in [1,2]"), x="filmeId",  y="nota")



# links de documentação e bibliotecas relacionadas com ciencia de dados!
#
#
#